### ISSUE TITLE
Gewählte Architektur beschreiben

### ISSUE THREAD

**Issue by SvNawesome** [SvNawesome/Project-Zero#11]

**Comment by ape97** [comment]
Unser Projekt wird in Java mit Unterstützung des Spring MVC und Hibernate Frameworks entwickelt, es wird eine webbasierende Oberfläche erhalten. Die Daten werden via Hibernate in einem MySQL-Server o.ä. serialisiert.

Aus dem Aufbau unserer Klassen ergibt sich folgende Architektur:

Die Wareneingang-Klasse sowie die Warenausgang-Klasse, kennen beide die Lieferant-Klasse und zwar immer in einer 1 : n Beziehung, desweiteren ist beiden Klassen die Bestandartikel-Klasse bekannt, so kann jedem Ein-/Ausgang Lieferanten und Artikel zugeordnet werden.

Der Bestandartikel-Klasse ist die Artikelstamm-Klasse bekannt (n : 1) und der Lieferant-Klasse ist diese ebenfalls (n : 1) bekannt.

Die Lager-Klasse fungiert auf ähnliche Weise, diese kennt die Bestandartikel-Klasse sowie diese die Lager-Klasse kennt (n : n) und zusätzlich kennt die Lager-Klasse die Mitarbeiter-Klasse in einer 1 : n Beziehung, dies hat den Grund das sich jedes Lager aus zu lagernden Artikeln und zuständigen Mitarbeitern zusammensetzt.
