### ISSUE TITLE
Was ist Gegenstand des Projektauftrags

### ISSUE THREAD

**Issue by SvNawesome** [SvNawesome/Project-Zero#4]

**Comment by srepke** [comment]
Das Projekt soll dem Anwender die Verwaltung von Artikel, Lager, Lagerplätze, Mitarbeiter, Wareneingänge, Lieferanten und der Warenausgänge ermöglichen und vereinfachen. Das System soll alles in einer Webbasierenden Anwendung, die übersichtlich und einfach gehalten ist, zur Verfügung stellen und eine möglichst intuitive Bedienung bieten.
