### ISSUE TITLE
Warum wurde dieser Auftrag gewählt?

### ISSUE THREAD

**Issue by SvNawesome** [SvNawesome/Project-Zero#5]

**Comment by ape97** [comment]
Wir haben uns für den Auftrag eines einfachen Warenwirtschaftssystems mit dem Schwerpunkt Lagerlogistik entschieden, weil wir es interessant und anregend finden uns mit dem verwalten und planen der verschiedenen Aufgaben bzw. Problemen (im Bereich Lagerlogistik) die auf ein Unternehmen im Tagesgeschäft zukommen zu beschäftigen.
