### ISSUE TITLE
Wo liegen die Vorteile/Nachteile

### ISSUE THREAD

**Issue by ape97** [SvNawesome/Project-Zero#68]

**Comment by finn31** [comment]
Die Vorteile eines Warenwirtschaftssystem bezogen auf Lagerlogistik sind zahlreich. Zum einen kann man durch das System eine einfache und schnelle Übersicht über die Lagerlogistik erhalten, sowie die Lagerbestände und Lieferanten verwalten. Dadurch wird die aufgebrachte Arbeitszeit zum Erfassen von wichtigen Faktoren verkürzt, da sie nicht mehr in schriftlicher Form vorhanden sind und somit das Suchen nach bestimmten Informationen weniger Zeit beansprucht.
Es ist zu jeder Zeit möglich festzustellen wie viele Lagerplätze noch frei sind und somit möglich effektiv zu planen. Außerdem ist es möglich durch das System explizite Arbeitsabläufe zu automatisieren, zum Beispiel das Erstellen von Angeboten, Aufträgen und Rechnungen. Zudem ist es möglich früh zu erkennen ob zusätzliche Lagerfläche benötigt wird.
Ein weiterer Vorteil ist die Einfachheit der Datenpflege, man muss nun nicht mehr alles per Zettel und Stift aufnehmen und kann es bequem über eine Oberfläche in das System einpflegen. Dies hilft dem Workflow der Mitarbeiter angenehmer zu gestalten.
Ein großer Nachteil ist die Aktualität des Systems, es muss täglich gepflegt werden um Missverständnisse und falsche bzw. doppelte Planung zu verhindern, welche einen wirtschaftlichen Verlust verursachen könnte. 
Des Weiteren können die Server abstürzen, welches die Verfügbarkeit des Systems einschränken würde. 
Zudem kann es passieren, dass eine fehlerhafte Planung auftritt, verursacht durch Bugs im System, welche Zeit benötigen um behoben zu werden und somit einen Stillstand des Systems herbeiführen würden. 
Zusätzlich werden Erhaltungskosten anfallen im Sinne von Stromkosten, Serviceverträge und Wartungskosten, welche bei der Beschaffung eines Warenwirtschaftssystem beachtet werden müssen.

(Von Sven)
