### ISSUE TITLE
Grundgerüst erstellen

### ISSUE THREAD

**Issue by ape97** [SvNawesome/Project-Zero#74]
Grundgerüst (packages, Testklassen, Controller, usw.) erstellen und ins Repository laden

**Comment by SvNawesome** [comment]
Erstes mal erstellt: 25.02.16
Servlets verwendet: 14.03.16
Servlets entfernt da es nicht dem SpringMVC Pattern entspricht : 17.03.16
Grundgerüst fertiggestellt: 17.03.16
