### ISSUE TITLE
IST-Analyse

### ISSUE THREAD

**Issue by SvNawesome** [SvNawesome/Project-Zero#8]

**Comment by flange94** [comment]
-   Händisch in Listen(Lagerbuch und Artikelliste)
-   Unsaubere Schreibweise/Jeder Mitarbeiter andere Handschrift
-   Hoher Zeit/hohe Arbeitsenergie
-   Listen gehen verloren/Mitarbeiter nimmt Liste ausversehen mit nach Hause/Papier hält nicht ewig – Keine Absicherung falls verloren/Daten sind dann weg
-   Listen liegen irgendwo im Lager rum/kein fester Platz
-   Die Listen sind nicht geordnet und man findet die Artikel nicht
-   Mitarbeiter hat vergessen einen Artikel in die Listen ein- bzw. auszutragen
-   Lagerlogistiker kündigt und nimmt Liste mit
-   Andere Mitarbeiter in der Firma müssen entweder ins Lager schauen oder den Lagerlogistiker fragen, ob ein Artikel vorhanden ist und ob eine Lieferung bereits angekommen ist
-   Für jeden Mitarbeiter müsste eine Artikelliste angefertigt werden
-   Sollte der Lagerlogistiker mal ausfallen(Krankheit o.ä.) ist es schwer jemanden neues einzuarbeiten

--> Stichworte zur IST-Analyse

**Comment by flange94** [comment]
Umbenannt in IST-Analyse.
Ticket #6 geschlossen und Ticket #7 auch.
Alles hier zusammenfügen.

**Comment by flange94** [comment]
Das Problem besteht darin, dass derzeit jegliche Lagerbuchung und jeder Artikel händisch in Listen auf Papier gepflegt sind. Durch die verschiedenen Handschriften der Mitarbeiter entsteht eine Liste, welche nicht durch jeden lesbar ist. Hinzu kommt, dass in Stressmomenten oder auch durch Müdigkeit die Listen sehr unsauber gepflegt werden. Dies alles kostet sehr viel Zeit und Arbeitsenergie. Noch mehr Zeit kostet es, wenn eine Liste verloren oder kaputt geht, da diese dann komplett neu erstellt werden müssen. Ab und zu passiert es auch, dass ein Mitarbeiter eine Liste mit in sein Büro bzw. mit nach Hause nimmt. Passiert das steht der Betrieb und es wird gewartet, bis die Liste wieder verfügbar ist. Auch gibt es für diese Listen keinen festen Platz im Lager, sodass diese immer gesucht werden müssen bevor man seine Aufgabe erledigen kann. Auch die Sortierung der Listen wird nicht immer ernst genommen und man muss erst einmal die richtige Liste finden. Hinzu kommt, dass die Listen nicht immer vollständig sind, da es passieren kann das ein Mitarbeiter etwas in die eine Liste einträgt, aber in einer anderen vergisst das hinzuzufügen. Zudem muss der Vertrieb jedes Mal wenn sie Daten benötigen im Lager nachfragen beziehungsweise ins Lager gehen und fragen ob ein Artikel da ist und wie viel. 

--> vorläufiger Text
