### ISSUE TITLE
Daos nach neuem Muster erstellen

### ISSUE THREAD

**Issue by finn31** [SvNawesome/Project-Zero#93]
Die DAOs nach dem neuen "Muster" erstellen (UserDAO und UserDAOImpl sind schon gemacht ggf. vorlage)

**Comment by SvNawesome** [comment]
angenommen 08.04.16

**Comment by finn31** [comment]
Habe alle DAOs erstellt allerdings sind sie noch nicht komplett fertig
28.04.16
